version: "3"

services:
  moodle-php:
    container_name: docker-moodle-php
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:80"
  
  mariadb:
    container_name: docker-moodle-mariadb
    image: mariadb:latest
    environment:
      MARIADB_USER: moodle
      MARIADB_PASSWORD: moodle
      MARIADB_ROOT_PASSWORD: moodle      
